from . import field_notebook_crop
from . import field_notebook_autonomy
from . import field_notebook_province
from . import field_notebook_town
from . import field_notebook_campaign
from . import field_notebook_variety
from . import field_notebook_plot_use
from . import field_notebook_zone
from . import field_notebook_system
from . import field_notebook_irrigation
from . import field_notebook_irrigation_system
from . import field_notebook_ucth
from . import field_notebook_parcel
from . import field_notebook_labor
from . import field_notebook_harvest
from . import field_notebook_labor_type
from . import field_notebook_performance
from . import field_notebook_phytosanitary
from . import field_notebook_phytosanitary_application_type
from . import field_notebook_exploitation
from . import res_partner
from . import field_notebook_enclosure
from . import equipment
from . import product
from . import res_company
from . import res_config_settings
from . import product_template_security_term
from . import product_template_dose
from . import field_notebook_confirmation
from . import field_notebook_agent
