from . import field_notebook_crop
from . import field_notebook_campaign
from . import field_notebook_variety
from . import field_notebook_plot_use
from . import field_notebook_zone
from . import field_notebook_system
from . import field_notebook_irrigation
from . import field_notebook_parcel
from . import field_notebook_exploitation
from . import res_partner
from . import field_notebook_enclosure
from . import equipment
